# Generated by Django 4.1.7 on 2023-03-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='creator_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
