# Generated by Django 4.1.7 on 2023-03-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentator',
        ),
        migrations.AddField(
            model_name='comment',
            name='book_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='commentator_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
