# Generated by Django 4.1.7 on 2023-03-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_comment_book_remove_comment_commentator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'fiction'), ('mystery', 'mystery'), ('adventure', 'adventure'), ('biography', 'biography')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
