# Generated by Django 4.1.7 on 2023-03-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentator_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentator_username',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
